# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StyleLoadSave
                                 A QGIS plugin
 Load and Save Current vector Layer Style
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-12
        copyright            : (C) 2023 by Giulio Fattori
        email                : g@g.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StyleLoadSave class from file StyleLoadSave.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .StyleLoadSave import StyleLoadSave
    return StyleLoadSave(iface)
